# Tsallis
# algorithm_name: iem_ppo
# learning_rate: 0.002
# eval_every: 100
# cuda: true
# num_envs: 8
# num_steps: 512
# anneal_lr: true
# gae: true
# gamma: 0.99
# gae_lambda: 0.95
# num_minibatches: 2
# update_epochs: 2
# norm_adv: true
# clip_coef: 0.05
# clip_vloss: true
# ent_coef: 0.20
# vf_coef: 0.0625
# max_grad_norm: 0.5
# target_kl: null
# iem_lr: 0.001
# alpha: 0.4
# beta: 0.5
# tsallis_q: 2.0
# policy_head: softmax

# # Shannon# 
algorithm_name: iem_ppo
learning_rate: 0.002
eval_every: 10
cuda: True
num_envs: 8
num_steps: 512
anneal_lr: true
gae: true
gamma: 0.99
gae_lambda: 0.95
num_minibatches: 2
update_epochs: 1
norm_adv: true
clip_coef: 0.05
clip_vloss: true
ent_coef: 0.1
vf_coef: 0.0625
max_grad_norm: 2.0
target_kl: null
iem_lr: 0.001
alpha: 0.5
beta: 3.0


