algorithm_name: iem_e_ppo
learning_rate: 0.002
eval_every: 100
cuda: true
num_envs: 24
num_steps: 512
anneal_lr: true
gae: true
gamma: 0.99
gae_lambda: 0.95
num_minibatches: 2
update_epochs: 1
norm_adv: true
clip_coef: 0.5
clip_vloss: true
ent_coef: 0.25
vf_coef: 0.0625
max_grad_norm: 3.0
target_kl: null
iem_lr: 0.001
alpha: 0.4
beta: 1.0
tsallis_q: 2.0
epsilon_start: 0.3
epsilon_end: 0.2
epsilon_decay_fraction: 0.99
epsilon_dead_tol: 0.1
