# # best hyperparam 
# algorithm_name: ppo  # Name of the algorithm
# learning_rate: 0.002  # the learning rate of the optimizer
# eval_every: 10  # evaluate the policy every N updates
# cuda: false  # matched to best config
# num_envs: 8  # the number of parallel game environments
# num_steps: 512  # the number of steps to run in each environment per policy rollout
# anneal_lr: true  # Toggle learning rate annealing for policy and value networks
# gae: true  # Use GAE for advantage computation
# gamma: 0.99  # the discount factor gamma
# gae_lambda: 0.95  # the lambda for the general advantage estimation
# num_minibatches: 2  # the number of mini-batches
# update_epochs: 1  # the K epochs to update the policy
# norm_adv: true  # Toggles advantages normalization
# clip_coef: 0.05  # the surrogate clipping coefficient
# clip_vloss: true  # Toggles whether or not to use a clipped loss for the value function
# ent_coef: 0.1  # coefficient of the entropy
# vf_coef: 0.0625  # coefficient of the value function
# max_grad_norm: 2.0  # the maximum norm for the gradient clipping
# target_kl: null  # the target KL divergence threshold

# Tsallis
algorithm_name: ppo
learning_rate: 0.002
eval_every: 100
cuda: true
num_envs: 8
num_steps: 512
anneal_lr: true
gae: true
gamma: 0.99
gae_lambda: 0.95
num_minibatches: 2
update_epochs: 2
norm_adv: true
clip_coef: 0.05
clip_vloss: true
ent_coef: 0.20
vf_coef: 0.0625
max_grad_norm: 0.5
target_kl: null
tsallis_q: 2.0