algorithm_name: ppo
anneal_lr: true
clip_coef: 0.4
clip_vloss: true
ent_coef: 0.2
gae: true
gae_lambda: 0.95
gamma: 0.99
learning_rate: 0.001
max_grad_norm: 0.5
norm_adv: true
num_envs: 8
num_minibatches: 16
num_steps: 1024
target_kl: null
update_epochs: 1
vf_coef: 4.0
